# Mappings

type_mapping = {
    'Co-Ferment': ['fruit', 'ferment'],
    'Orange': ['orange', 'contact'],
    'Piquette': 'piquette',
    'Red': 'red',
    'Ros&#233;': ['rose', 'ros'],
    'Sparkling': ['sparkling', 'champagne', 'pet-nat'],
    'White': 'white'
}

region_mapping = {
    'Argentina': 'argentina',
    'Australia': 'australia',
    'Austria': 'austria',
    'California': 'california',
    'Chile': 'chile',
    'Corsica': 'corsica',
    'Eastern Europe': 'eastern',
    'France': ['france', 'french'],
    'Georgia': 'georgia',
    'Germany': 'germany',
    'Greece': 'greece',
    'Italy': ['italy', 'italian'],
    'Lebanon': 'lebanon',
    'Morocco': 'morocco',
    'Oregon': 'oregon',
    'South Africa': 'south+africa',
    'Southern Hemisphere': 'hemisphere',
    'Spain + Portugal': ['spain', 'spanish', 'portugal', 'portuguese'],
    'United States': ['usa', 'united+states', 'domestic']
}

maker_mapping = {
    'Adelante': 'adelante',
    'Amevive': 'amevive',
    'Ampeleia': 'ampeleia',
    'Amplify': 'amplify',
    'Art And Science': 'artandscience',
    'Azul Y Garanza': 'azulygaranza',
    'Bichi': 'bichi',
    'Bojo Do Luar': 'bojodoluar',
    'Broc Cellars': 'broc',
    'Buddy Buddy': 'buddybuddy',
    'Canetta': 'canetta',
    'Cantina Giardino': 'cantinagiardino',
    'Cantina Marilina': 'cantinamarilina',
    'Christina': 'christina',
    'Cirelli': 'cirelli',
    'Costadila': 'costadila',
    'Das Glitz': 'dasglitz',
    'De Levende': 'delevende',
    'Delinquente': 'delinquente',
    'Deux Punx': 'deuxpunx',
    'Donkey & Goat': 'donkey',
    'Due Terre': 'dueterre',
    'Echeverria': 'echeverria',
    'Ercole': 'ercole',
    'Es Okay': 'esokay',
    'Field Recordings': 'fieldrecordings',
    'Florez': 'florez',
    'Folk Machine': 'folkmachine',
    'Folktale': 'folktale',
    'Forlorn Hope': 'forlorn',
    'Furlani': 'furlani',
    'Gatto Brio': 'gattobrio',
    'Gearhead': 'gearhead',
    'Gentle Folk': 'gentle folk',
    'Good Boy Wine': 'goodboy',
    'Gulp Hablo': 'gulp',
    'Gut Oggau': 'gutoggau',
    'Hammerling': 'hammerling',
    'Indigeno': 'indigeno',
    'Iruai': 'iruai',
    'J. Brix': ['jbrix', 'j.brix',],
    'Jumbo Time Wines': 'jumbotime',
    'Jumping Juice': 'jumpingjuice',
    'Keltis': 'keltis',
    'Kindeli': 'kindeli',
    'Koehnen': 'koehnen',
    'Kolfok': 'kolfok',
    'Kopptisch': 'kopptisch',
    'Las Jaras': 'lasjaras',
    'Le Coste': 'lecoste',
    'Le Machin': 'lemachin',
    'Les Deux Moulins': 'lesdeuxmoulins',
    'Les Lunes': 'leslunes',
    'Lo-Fi': 'lo-fi',
    'Luca Bevilacqua': 'lucabevilacqua',
    'Lumina': 'lumina',
    'Mae Son': 'maeson',
    'Margins': 'margins',
    'Marigny': 'marigny',
    'Martha Stoumen': 'marthastoumen',
    'Meinklang': 'meinklang',
    'Nestarec': 'nestarec',
    'Nice Beverage Co': 'nicebeverage',
    'Oeno': 'oeno',
    'Old Westminster': 'oldwestminster',
    'Old World Winery': 'oldworld',
    'Papras': 'papras',
    'Patrick Sullivan': 'patricksullivan',
    'Pavette': 'pavette',
    'Pielihueso': 'pielihueso',
    'Pirouettes': 'pirouette',
    'Populis': 'populis',
    'Purity': 'purity',
    'Raimones': 'raimones',
    'Ruth Lewandowski': 'lewandowski',
    'Scotty Boy': ['scottyboy', 'scotty-boy'],
    'So Far Out': 'sofarout',
    'Stagiaire': 'stagiaire',
    'Stolpman': 'stolpman',
    'Subject To Change': 'subjecttochange',
    'Swick': 'swick',
    'Teutonic': 'teutonic',
    'Trail Marker': 'trailmarker',
    'Union Sacre': 'unionsacre',
    'Vinos Pijoan': 'vinospijoan',
    'Viteadovest': 'viteadovest',
    'Wavy Wines': 'wavywines',
    'Wenzel Lockvogel': 'wenzellockvogel',
    'Wild Arc': 'wildarc',
    'Wonderwall': 'wonderwall',
    'Wonderwerk': 'wonderwerk',
    'Yetti & The Kokonut': 'yetti',
    'Ziniel': 'ziniel',
    'Zumo': 'zumo'
}