# Mappings

type_mapping = {
    'Co-Ferment': ['fruit', 'ferment'],
    'Orange': ['orange', 'contact'],
    'Piquette': 'piquette',
    'Red': 'red',
    'Ros&#233;': ['rose', 'ros'],
    'Sparkling': ['sparkling', 'champagne', 'pet-nat', 'pet+nat'],
    'White': 'white'
}

region_mapping = {
    'Argentina': ['argentina', 'argentine', 'argentinian'],
    'Australia': ['australia', 'australian'],
    'Austria': ['austria', 'austrian'],
    'California': ['california', 'californian'],
    'Chile': ['chile', 'chilean'],
    'Corsica': ['corsica', 'corsican'],
    'Eastern Europe': 'eastern',
    'France': ['france', 'french'],
    'Georgia': ['georgia', 'georgian'],
    'Germany': ['germany', 'german'],
    'Greece': ['greece', 'greek'],
    'Italy': ['italy', 'italian'],
    'Lebanon': ['lebanon', 'lebanese'],
    'Morocco': ['morocco', 'moroccan'],
    'Oregon': ['oregon', 'oregonian'],
    'South Africa': ['south+africa', 'southafrica', 'africa'],
    'Southern Hemisphere': 'hemisphere',
    'Spain': ['spain', 'spanish'],
    'Portugal': ['portugal', 'portuguese'],
    'United States': ['usa', 'united+states', 'unitedstates', 'domestic']
}

general_region_mapping = {
    'France': ['chateau', 'château', 'domaine', 'domäne', 'francois', 'les'],
    'Germany': ['weingut'],
    'Italy': ['cantina', 'monte'],
}

maker_mapping = {

    # A
    'Abbondanza': 'abbondanza',
    'Absentee': 'absentee',
    'Accenti': 'accenti',
    'Acri Wine': 'acriwine',
    'Adelante': 'adelante',
    'Aldinger': 'aldinger',
    'Alessandro Viola': 'alessandroviola',
    'Alfredo Maestro': 'domaestro',
    'Altar Uco': 'altaruco',
    'Amevive': 'amevive',
    'Ameztoi Txakolina': 'ameztoi',
    'Ampeleia': 'ampeleia',
    'Amplify': 'amplify',
    'Angeleno Wine Co': 'angeleno',
    'Angelo Negro': 'angelonegro',
    'Anonimas': 'anonimas',
    'Ardure Wines': 'ardure',
    'Art + Science': ['artandscience', 'artscience', 'art+science', 'art&science'],
    'Artesano Vintner': 'artesano',
    'Ashanta': 'ashanta',
    'Ashkahn': 'ashkahn',
    'Augur': 'augur',
    'Averaen': 'averaen',
    'Ayunta': 'ayunta',
    'Azimut': 'azimut',
    'Azul y Garanza': 'azulygaranza',

    # B
    'Badger Mountain': 'badger',
    'Banyan': 'banyan',
    'Baptiste Cousin': 'baptistecousin',
    'Barolo': 'barolo',
    'Bernabeleva': 'bernabeleva',
    'Between Us': 'betweenus',
    'Bichi': 'bichi',
    'Birichino': 'birichino',
    'Black Sheep Finds': ['blacksheep', 'hocuspocus'],
    'Bobinet': 'bobinet',
    'Bodan Roan': 'bodanroan',
    'Bojo Do Luar': ['bojodoluar', 'bojoduluar'],
    'Bonhomme': 'bonhomme',
    'Borachio': 'borachio',
    'Brea': 'brea',
    'Broc Cellars': 'broc',
    'Brooks': 'brooks',
    'Bruno Duchene': 'brunoduchene',
    'Buddy Buddy': ['buddybuddy', 'buddy-buddy', 'buddy/buddy'],
    'Bura': 'bura',

    # C
    'Caduceus': 'caduceus',
    'Caleb Leisure': 'calebleisure',
    'Cameron Winery': 'cameron',
    'Camp': 'camp',
    'Camuna Cellars': 'camuna',
    'Canetta': 'canetta',
    'Cantina Giardino': 'cantinagiardino',
    'Cantina Indigeno': 'indigeno',
    'Cantina Marilina': 'cantinamarilina',
    'Carlisle': 'carlisle',
    'Cat + Pierre Breton': 'breton',
    'Catalina Ugarte': 'catalinaugarte',
    'Cellario': 'cellario',
    'Cesca Daniele': 'cescadaniele',
    'Chateau Coujan': 'coujan',
    'Château de Roquefort': 'roquefort',
    'Chemins de Bassac': 'cheminsdebassac',
    'Christina': 'christina',
    'Cirelli': 'cirelli',
    'Clos Roussely': 'closroussely',
    'Collichio': 'collichio',
    'Colombaia': 'colombaia',
    'Controvento': 'controvento',
    'Costadilà': ['costadila', 'costadilà'],
    'Costador': 'costador',
    'Crosby': 'crosby',
    'Crowley': 'crowley',
    'Cuve Kollektiv': 'cuvekollektiv',

    # D
    "D' Estezargues": 'estezargues',
    'Daulhiac': 'daulhiac',
    'Day Wines': 'daywines',
    'De Levende': 'delevende',
    'Delinquente': 'delinquente',
    'Delta': 'delta',
    'Denny Bini': 'dennybini',
    'Deux Punx': 'deuxpunx',
    'Diel': 'diel',
    'Dinamo': 'dinamo',
    'Division': 'division',
    'Domaine Carterole': 'carterole',
    'Domaine de la Damase': 'damase',
    'Domaine de Majas': 'majas',
    'Domaine des Grottes': 'desgrottes',
    'Domaine Fouet': 'fouet',
    'Domaine Jacky Marteau': 'jackymarteau',
    'Domaine Mann': 'mann',
    'Domäne Vincendeau': 'vincendeau',
    'Donkey + Goat': 'donkey',
    'Donnhoff': 'donnhoff',
    'Doric': 'doric',
    'Dos Minas': 'dosminas',
    'Duckman': 'duckman',
    'Due Terre': 'dueterre',

    # E
    'Ebb Tide': 'ebbtide',
    'Echeverria': 'echeverria',
    'Edgar Brutler': 'brutler',
    'EK Wines': 'ekwines',
    'Elqui Wines': 'elqui',
    'Emme Wines': 'emme',
    'En Cavale': 'encavale',
    'Entre Vinyes': 'entrevinyes',
    'Ercole': 'ercole',
    'Eric Kent': 'erickent',
    'Eric Texier': 'texier',
    'Es Okay': 'esokay',
    'Etteilla Wines': 'etteilla',
    'Etz': 'etz',

    # F
    'Fable': 'fable',
    'Fanatic Wine Company': 'fanatic',
    'Field Recordings': 'fieldrecordings',
    'Filippo': 'filippo',
    'Flavia': 'flavia',
    'Florez': 'florez',
    'Folk Machine': 'folkmachine',
    'Folktale': 'folktale',
    'Forlorn Hope': 'forlorn',
    'Formiche': 'formiche',
    'Fossil + Fawn': 'fossil',
    'Franchere': ['franchere', 'francherre'],
    'Francois Ducrot': 'ducrot',
    'Francois Saint-Lo': ['saint-lo','saintlo'],
    'Frank Cornelissen': 'cornelissen',
    'Fresh Wines': 'fres.co',
    'Früg': ['frug', 'früg'],
    'Furlani': 'furlani',
    'Fuso': 'fuso',

    # G
    'Ganevat': 'ganevat',
    'Garalis': 'garalis',
    'Garcia Perez': 'garciaperez',
    "Garo'Vin": ["garo'vin", 'garovin', 'garo'],
    'Gaspard': 'gaspard',
    'Gatti': 'gatti',
    'Gatto': 'gatto',
    'Gearhead': 'gearhead',
    'Gentle Folk': 'gentlefolk',
    'Glinavos': 'glinavos',
    'Gogo': 'gogo',
    'Good Boy Wine': 'goodboy',
    'Gota': 'gota',
    'Gotsa': 'gotsa',
    'Gregoire Hoppenot': 'hoppenot',
    'Groundwork': 'groundwork',
    'Guilhem': 'guilhem',
    'Gulp Hablo': 'gulp',
    'Gut Oggau': 'gutoggau',

    # H
    'Haden Fig': 'hadenfig',
    'Halkia': 'halkia',
    'Hammerling': 'hammerling',
    'Hannes + Claudiu': 'claudiu',
    'Haru': 'haru',
    'Hanson Vineyards': 'hanson',
    'Herve Villemade': 'villemade',
    'Heya Wines': 'heya',
    'Hiedler': 'hiedler',
    'Hommage a Luise': 'hommagealuise',

    # I
    'Idlewild': 'idlewild',
    'Il Farneto': 'ilfarneto',
    'Il Folicello': 'ilfolicello',
    'Il Mostro': 'ilmostro',
    'Il Poggio': 'ilpoggio',
    'Il Vinco': 'ilvinco',
    'Inizi Wines': 'inizi',
    'Iruai': 'iruai',

    # J
    'J. Brix': ['jbrix', 'j.brix',],
    'Jan-Philipp Bleeke': 'bleeke',
    'J Mourat': 'mourat',
    'Johan': 'johan',
    'Jolie-Laide': ['jolielaide', 'jolie-laide'],
    'Jouves + Croisille': 'jouves',
    'Judith Beck': 'judithbeck',
    'Jumbo Time Wines': 'jumbotime',
    'Jumping Juice': 'jumpingjuice',

    # K
    'Karim Vionnet': 'vionnet',
    'Keltis': 'keltis',
    'Kermit Lynch': 'kermitlynch',
    'Kindeli': 'kindeli',
    'Kleines Gut': 'kleinesgut',
    'Kobal': 'kobal',
    'Koehnen': 'koehnen',
    'Kolfok': 'kolfok',
    'Kontozisis': 'kontozisis',
    'Koppitsch': ['koppitsch', 'kopptisch'],
    'Krenn49': 'krenn49',
    'Kumusha': 'kumusha',

    # L
    "L' Absurde Genie des Fleurs": 'absurdegenie',
    "L' Alezan": 'alezan',
    'La Boissiere': 'laboissiere',
    'La Cattiva': 'lacattiva',
    'La Clarine Farm': 'laclarinefarm',
    'Lady Of The Sunshine': 'ladyofthesunshine',
    'Laherte Frères': 'laherte',
    'La Liquiere': 'laliquiere',
    'La Lunotte': 'lalunotte',
    'Land of Saints': 'landofsaints',
    'La Patience': 'lapatience',
    'La Pétite Odyssée': 'odys',
    'La Salada': 'lasalada',
    'Las Jaras': 'lasjaras',
    'La Teuf': 'lateuf',
    'Le Coste': 'lecoste',
    'Le Coeur de la Reine': 'coeurdelareine',
    'Leiner': 'leiner',
    'Le Machin': 'lemachin',
    'Les Athletes du Vin': 'athletes',
    'Les Bories Jefferies': 'boriesjefferies',
    'Les Croisille': 'lescroisille',
    'Les Deux Moulins': 'lesdeuxmoulins',
    'Les Equilibristes': 'equilibristes',
    'Les Lunes': 'leslunes',
    'Les Tetes': 'lestetes',
    'Libertine Wines': 'libertine',
    'Licence IV': 'licenceiv',
    'Lieu Dit': 'lieudit',
    'Limited Addition': 'limitedaddition',
    'Limus': 'limus',
    'Lo-Fi': 'lo-fi',
    'Lornano': 'lornano',
    'Los Angeles River': 'angelesriver',
    'Los Conejos': 'losconejos',
    'Lubanzi': 'lubanzi',
    'Luca Bevilacqua': ['bevilacqua','belilacqua'],
    'Luc Lapeyre': 'luclapeyre',
    'Lumina': 'lumina',
    'Luuma': 'luuma',

    # M
    'Madson Wines': 'madson',
    'Mae Son': 'maeson',
    'Maison Angelot': 'angelot',
    'Maison Stéphan': ['maisonstephan', 'maisonstéphan'],
    'Makaridze': 'makaridze',
    'Maker': 'maker',
    'Maloof': 'maloof',
    'Marcio Lopes Vinho': 'marciolopes',
    'Margins': 'margins',
    'Marigny': 'marigny',
    'Markogianni': 'markogianni',
    'Marko Gure Arbasoak': 'markogure',
    'Martha Stoumen': 'marthastoumen',
    'Mas Blanch': 'masblanch',
    'Mas Candi': 'mascandi',
    'Mataroa': 'mataroa',
    'Matthiasson': 'matthiasson',
    'Matias Riccitelli': 'riccitelli',
    'Matic': 'matic',
    'Matthieu Barret': 'matthieubarret',
    'Maurer': 'maurer',
    'Max Dexheimer': 'dexheimer',
    'Meinklang': 'meinklang',
    'Mendall': 'mendall',
    'Mersel': 'mersel',
    'Milan Nestarec': 'nestarec',
    'Miles Garrett': 'milesgarrett',
    'Momento Mori': 'momentomori',
    'Mommenpop': 'mommenpop',
    'Monte Bernardi': 'montebernardi',
    'Montepeloso': 'montepeloso',

    # N
    'Nice Beverage Co': 'nicebeverage',
    'Nikalas Marani': 'nikalasmarani',
    'Nikolaihof': 'nikolaihof',
    'Notre Terre': 'notreterre',

    # O
    'Occidental': 'occidental',
    'Ocho': 'ocho',
    'Oda Family': 'odafamily',
    'Oeno': 'oeno',
    'Oest': 'oest',
    'Old Westminster': 'oldwestminster',
    'Old World Winery': 'oldworld',
    'Onward': 'onward',
    'Orbis Moderandi': 'orbis',
    'Orgo Dilao': 'orgodilao',
    'Ori Marani': 'orimarani',
    'Oro Di Diamanti': 'orodidiamanti',
    'Osa Major': 'osamajor',
    'Ott': 'ottam',
    'Outward Wines': 'outwardwines',
    'Ovum': 'ovum',

    # P
    'Papras': 'papras',
    'Patrick Sullivan': 'patricksullivan',
    'Pavette': 'pavette',
    'Pépin': ['pepin', 'pépin'],
    "Pheasant's Tears": 'pheasant',
    'Pielihueso': 'pielihueso',
    'Pierre Richard': 'pierrerichard',
    'Pirouettes': 'pirouette',
    'Podere il Saliceto': 'podereilsaliceto',
    'Poe': 'poe',
    'Poggio Delle Baccanti': 'baccanti',
    'Pollerhof': 'pollerhof',
    'Populis': 'populis',
    'Preston': 'preston',
    'Primitivus': 'primitivus',
    'Prisma': 'prisma',
    'Purity': 'purity',

    # R
    'Raimones': 'raimones',
    'Ram Cellars': 'ramcellars',
    'Ramón Jané': ['ramonjane', 'ramónjané', 'ramonjané', 'ramónjane'],
    'Rarefratte': 'rarefratte',
    'Ribela': 'ribela',
    'Richvale': 'richvale',
    'Rocco Di Carpeneto': 'roccodicarpeneto',
    'Rogue Vine': 'roguevine',
    'Ruth Lewandowski': 'lewandowski',

    # S
    'Sage Rat': 'sagerat',
    'Samuel Boulay': 'samuelboulay',
    'Sassara': 'sassara',
    'Savee Sea': 'saveesea',
    'Saxum': 'saxum',
    'Scala': 'scala',
    'Scar of the Sea': 'scarofthesea',
    'Schlossmuhlenhof': 'schlossmuhlenhof',
    'Schweizer': 'schweizer',
    'Scotty Boy': ['scottyboy', 'scotty-boy'],
    'Scribe Winery': 'scribe',
    'Selbach Oster': 'selbachoster',
    'Sete': 'sete',
    'Sfera': 'sfera',
    'Sheild': 'sheild',
    'Silvio Messana': 'silviomessana',
    'So Far Out': 'sofarout',
    'Sonshine Vins': 'sonshine',
    'Southhold Farm + Cellar': 'southhold',
    'Smallfry': 'smallfry',
    'Split Rail': 'splitrail',
    'St. Reginald Parish': 'reginald',
    'Staffelter Hof': 'staffelterhof',
    'Stagiaire': 'stagiaire',
    'Stamnaki': 'stamnaki',
    'Straka': 'straka',
    'Stolpman': 'stolpman',
    'Subject To Change': 'subjecttochange',
    'Super Real Wines': 'superreal',
    'Swick': 'swick',

    # T
    'Tavijn': 'tavijn',
    'Tenuta': 'tenuta',
    'Teutonic': 'teutonic',
    'Central Coast Group': 'centralcoastgroup',
    'Thomas Puechavy': 'thomaspuechavy',
    'Thomas Santamaria': 'thomassantamaria',
    'Tiberi': 'tiberi',
    'Topanga Vineyards': 'topanga',
    'Trail Marker': 'trailmarker',
    'Tre Monti': 'tremonti',
    'Troupis': 'troupis',
    'Turley': 'turley',
    'Two Shepherds': 'twoshepherds',
    'Tzora Vineyards': ['tzora', 'judeanhills'],

    # U
    'Ultraviolet': 'ultraviolet',
    'Umathum': 'umathum',
    'Union Sacre': 'unionsacre',

    # V
    'Valerie Forgues': 'valerieforgues',
    'Valravn': 'valravn',
    'Vina Maitia': 'maitia',
    'Vinca Minor': 'vincaminor',
    'Vin De California': 'vindecalifornia',
    'Vini Rabasco': 'rabasco',
    'Vino Lauria': 'vinolauria',
    'Vinos Pijoan': 'vinospijoan',
    'Vinovore': 'vinovore',
    'Vins Nus': 'vinsnus',
    'Vinyer De La Ruca': 'vinyerdelaruca',
    'Viteadovest': 'viteadovest',
    'Vivanterre': 'vivanterre',

    # W
    'Walter Scott': 'walterscott',
    'Wavy Wines': 'wavywines',
    'Weingut Edelberg': ['weingut', 'das'],
    'Weinschach': 'weinschach',
    'Weninger': 'weninger',
    'Wenzel': 'wenzel',
    'Wild Arc': 'wildarc',
    'Williams Selyem': 'williamsselyem',
    'Wohlgemuthheim': 'wohlgemuthheim',
    'Wonderland Project': 'wonderland',
    'Wonderwall': 'wonderwall',
    'Wonderwerk': 'wonderwerk',

    # Y
    'Yetti + The Kokonut': 'yetti',

    # Z
    'Zebedeo': 'zebedeo',
    'Zeit': 'zeit',
    'Zillamina': 'zillamina',
    'Ziniel': 'ziniel',
    'Zumo': 'zumo'
}

origin_mapping = {

    # A
    'Abbondanza': 'Italy',
    'Absentee': 'California',
    'Accenti': 'California',
    'Acri Wine': 'California',
    'Adelante': 'Argentina',
    'Aldinger': 'Germany',
    'Alessandro Viola': 'Italy',
    'Alfredo Maestro': 'Spain',
    'Amevive': 'California',
    'Altar Uco': 'Argentina',
    'Ameztoi Txakolina': 'Spain',
    'Ampeleia': 'Italy',
    'Amplify': 'California',
    'Angeleno Wine Co': 'California',
    'Angelo Negro': 'Italy',
    'Anonimas': 'Spain',
    'Ardure Wines': 'California',
    'Art + Science': 'Oregon',
    'Artesano Vintner': 'Spain',
    'Ashanta': 'California',
    'Ashkahn': 'California',
    'Augur': 'California',
    'Averaen': 'Oregon',
    'Ayunta': 'Italy',
    'Azimut': 'Spain',
    'Azul y Garanza': 'Spain',

    # B
    'Badger Mountain': 'Washington',
    'Banyan': 'California',
    'Baptiste Cousin': 'France',
    'Barolo': 'Italy',
    'Bernabeleva': 'Spain',
    'Between Us': 'Italy',
    'Bichi': 'Mexico',
    'Birichino': 'California',
    'Black Sheep Finds': 'California',
    'Bobinet': 'France',
    'Bodan Roan': 'California',
    'Bojo Do Luar': 'Portugal',
    'Bonhomme': 'France',
    'Borachio': 'Australia',
    'Brea': 'California',
    'Broc Cellars': 'California',
    'Brooks': 'Oregon',
    'Bruno Duchene': 'France',
    'Buddy Buddy': 'California',
    'Bura': 'Croatia',

    # C
    'Caduceus': 'Arizona',
    'Caleb Leisure': 'California',
    'Cameron Winery': 'Oregon',
    'Camp': 'California',
    'Camuna Cellars': 'Philadelphia',
    'Canetta': 'Spain',
    'Cantina Giardino': 'Italy',
    'Cantina Indigeno': 'Italy',
    'Cantina Marilina': 'Italy',
    'Carlisle': 'California',
    'Cat + Pierre Breton': 'France',
    'Catalina Ugarte': 'Chile',
    'Cellario': 'Italy',
    'Cesca Daniele': 'Italy',
    'Chateau Coujan': 'France',
    'Château de Roquefort': 'France',
    'Chemins de Bassac': 'France',
    'Christina': 'Austria',
    'Cirelli': 'Italy',
    'Clos Roussely': 'France',
    'Collichio': 'Italy',
    'Colombaia': 'Italy',
    'Controvento': 'Italy',
    'Costadilà': 'Italy',
    'Constador': 'Spain',
    'Crosby': 'California',
    'Crowley': 'Oregon',
    'Cuve Kollektiv': 'Germany',

    # D
    "D' Estezargues": 'France',
    'Daulhiac': 'France',
    'Day Wines': 'Oregon',
    'De Levende': 'California',
    'Delinquente': 'Australia',
    'Delta': 'California',
    'Denny Bini': 'Italy',
    'Deux Punx': 'California',
    'Diel': 'Germany',
    'Dinamo': 'Italy',
    'Division': 'Oregon',
    'Domaine Carterole': 'France',
    'Domaine de la Damase': 'France',
    'Domaine de Majas': 'France',
    'Domaine des Grottes': 'France',
    'Domaine Fouet': 'France',
    'Domaine Jacky Marteau': 'France',
    'Domaine Mann': 'France',
    'Domäne Vincendeau': 'France',
    'Donkey + Goat': 'California',
    'Donnhoff': 'Germany',
    'Doric': 'Greece',
    'Dos Minas': 'Argentina',
    'Duckman': 'Portugal',
    'Due Terre': 'Italy',

    # E
    'Ebb Tide': 'Oregon',
    'Echeverria': 'Chile',
    'Edgar Brutler': 'Romania',
    'EK Wines': 'California',
    'Elqui Wines': 'Chile',
    'Emme Wines': 'California',
    'En Cavale': 'California',
    'Entre Vinyes': 'Spain',
    'Ercole': 'Italy',
    'Eric Kent': 'California',
    'Eric Texier': 'France',
    'Es Okay': 'California',
    'Etteilla Wines': 'California',
    'Etz': 'Austria',

    # F
    'Fable': 'California',
    'Fanatic Wine Company': 'California',
    'Field Recordings': 'California',
    'Filippo': 'Italy',
    'Flavia': 'Italy',
    'Florez': 'California',
    'Folk Machine': 'California',
    'Folktale': 'California',
    'Forlorn Hope': 'California',
    'Formiche': 'Italy',
    'Fossil + Fawn': 'Oregon',
    'Franchere': 'Oregon',
    'Francois Ducrot': 'France',
    'Francois Saint-Lo': 'France',
    'Frank Cornelissen': 'Italy',
    'Fresh Wines': 'California',
    'Früg': 'Austria',
    'Furlani': 'Italy',
    'Fuso': 'Italy',

    # G
    'Ganevat': 'France',
    'Garalis': 'Greece',
    'Garcia Perez': 'Spain',
    "Garo'Vin": 'France',
    'Gaspard': 'France',
    'Gatti': 'Italy',
    'Gatto': 'Italy',
    'Gearhead': 'California',
    'Gentle Folk': 'Australia',
    'Glinavos': 'Greece',
    'Gogo': 'Georgia',
    'Good Boy Wine': 'California',
    'Gota': 'Portugal',
    'Gotsa': 'Georgia',
    'Gregoire Hoppenot': 'France',
    'Groundwork': 'California',
    'Guilhem': 'France',
    'Gulp Hablo': 'Spain',
    'Gut Oggau': 'Austria',

    # H
    'Haden Fig': 'Oregon',
    'Halkia': 'Greece',
    'Hammerling': 'California',
    'Hannes + Claudiu': 'Germany',
    'Haru': 'France',
    'Hanson Vineyards': 'Oregon',
    'Herve Villemade': 'France',
    'Heya Wines': 'Lebanon',
    'Hiedler': 'Austria',
    'Hommage a Luise': 'Germany',

    # I
    'Idlewild': 'California',
    'Il Farneto': 'Italy',
    'Il Folicello': 'Italy',
    'Il Mostro': 'Italy',
    'Il Poggio': 'Italy',
    'Il Vinco': 'Italy',
    'Inizi Wines': 'California',
    'Iruai': 'California',

    # J
    'J. Brix': 'California',
    'Jan-Philipp Bleeke': 'Germany',
    'J Mourat': 'France',
    'Johan': 'Oregon',
    'Jolie-Laide': 'California',
    'Jouves + Croisille': 'France',
    'Judith Beck': 'Austria',
    'Jumbo Time Wines': 'California',
    'Jumping Juice': 'Australia',

    # K
    'Karim Vionnet': 'France',
    'Keltis': 'Slovenia',
    'Kermit Lynch': 'France',
    'Kindeli': 'New Zealand',
    'Kleines Gut': 'Germany',
    'Kobal': 'Slovenia',
    'Koehnen': 'California',
    'Kolfok': 'Austria',
    'Kontozisis': 'Greece',
    'Koppitsch': 'Austria',
    'Krenn49': 'Austria',
    'Kumusha': 'South Africa',

    # L
    "L' Absurde Genie des Fleurs": 'France',
    "L' Alezan": 'France',
    'La Boissiere': 'France',
    'La Cattiva': 'Italy',
    'La Clarine Farm': 'California',
    'Lady Of The Sunshine': 'California',
    'Laherte Frères': 'France',
    'La Liquiere': 'France',
    'La Lunotte': 'France',
    'Land of Saints': 'California',
    'La Patience': 'France',
    'La Pétite Odyssée': 'France',
    'La Salada': 'Spain',
    'Las Jaras': 'California',
    'La Teuf': 'France',
    'Le Coste': 'Italy',
    'Le Coeur de la Reine': 'France',
    'Leiner': 'Germany',
    'Le Machin': 'California',
    'Les Athletes du Vin': 'France',
    'Les Bories Jefferies': 'France',
    'Les Croisille': 'France',
    'Les Deux Moulins': 'France',
    'Les Equilibristes': 'France',
    'Les Lunes': 'California',
    'Les Tetes': 'France',
    'Libertine Wines': 'Oregon',
    'Licence IV': 'France',
    'Lieu Dit': 'California',
    'Limited Addition': 'Oregon',
    'Limus': 'Australia',
    'Lo-Fi': 'California',
    'Lornano': 'Italy',
    'Los Angeles River': 'California',
    'Los Conejos': 'Spain',
    'Lubanzi': 'South Africa',
    'Luca Bevilacqua': 'Italy',
    'Luc Lapeyre': 'France',
    'Lumina': 'California',
    'Luuma': 'California',

    # M
    'Madson Wines': 'California',
    'Mae Son': 'Italy',
    'Maison Angelot': 'France',
    'Maison Stéphan': 'France',
    'Makaridze': 'Georgia',
    'Maker': 'California',
    'Maloof': 'Oregon',
    'Marcio Lopes Vinho': 'Portugal',
    'Margins': 'California',
    'Marigny': 'Oregon',
    'Markogianni': 'Greece',
    'Marko Gure Arbasoak': 'Spain',
    'Martha Stoumen': 'California',
    'Mas Blanch': 'Spain',
    'Mas Candi': 'Spain',
    'Mataroa': 'Greece',
    'Matthiasson': 'California',
    'Matias Riccitelli': 'Argentina',
    'Matic': 'Slovenia',
    'Matthieu Barret': 'France',
    'Maurer': 'Serbia',
    'Max Dexheimer': 'Germany',
    'Meinklang': 'Austria',
    'Mendall': 'Spain',
    'Mersel': 'Lebanon',
    'Milan Nestarec': 'Czech Republic',
    'Miles Garrett': 'California',
    'Momento Mori': 'California',
    'Mommenpop': 'California',
    'Monte Bernardi': 'Italy',
    'Montepeloso': 'Italy',

    # N
    'Nice Beverage Co': 'South Africa',
    'Nikalas Marani': 'Georgia',
    'Nikolaihof': 'Austria',
    'Notre Terre': 'France',

    # O
    'Occidental': 'California',
    'Ocho': 'Georgia',
    'Oda Family': 'Georgia',
    'Oeno': 'California',
    'Oest': 'California',
    'Old Westminster': 'Maryland',
    'Old World Winery': 'California',
    'Onward': 'California',
    'Orbis Moderandi': 'New Zealand',
    'Orgo Dilao': 'Georgia',
    'Ori Marani': 'Georgia',
    'Oro Di Diamanti': 'Italy',
    'Osa Major': 'California',
    'Ott': 'Austria',
    'Outward Wines': 'California',
    'Ovum': 'Oregon',

    # P
    'Papras': 'Greece',
    'Patrick Sullivan': 'Australia',
    'Pavette': 'California',
    'Pépin': 'France',
    "Pheasant's Tears": 'Georgia',
    'Pielihueso': 'Argentina',
    'Pierre Richard': 'France', 
    'Pirouettes': 'France',
    'Podere il Saliceto': 'Italy',
    'Poe': 'California',
    'Poggio Delle Baccanti': 'Italy',
    'Pollerhof': 'Austria',
    'Populis': 'California',
    'Preston': 'California',
    'Primitivus': 'Italy',
    'Prisma': 'Chile',
    'Purity': 'California',

    # R
    'Raimones': 'Spain',
    'Ram Cellars': 'Washington',
    'Ramón Jané': 'Spain',
    'Rarefratte': 'Italy',
    'Ribela': 'Spain',
    'Richvale': 'California',
    'Rocco Di Carpeneto': 'Italy',
    'Rogue Vine': 'Chile',
    'Ruth Lewandowski': 'California',

    # S
    'Sage Rat': 'Washington',
    'Samuel Boulay': 'France',
    'Sassara': 'Italy',
    'Savee Sea': 'New Zealand',
    'Saxum': 'California',
    'Scala': 'Italy',
    'Scar of the Sea': 'California',
    'Schlossmuhlenhof': 'Germany',
    'Schweizer': 'Germany',
    'Scotty Boy': 'California',
    'Scribe Winery': 'California',
    'Selbach Oster': 'Germany',
    'Sete': 'Italy',
    'Sfera': 'Italy',
    'Sheild': 'New Zealand',
    'Silvio Messana': 'Italy',
    'So Far Out': 'California',
    'Sonshine Vins': 'France',
    'Southhold Farm + Cellar': 'Texas',
    'Smallfry': 'Australia',
    'Split Rail': 'Idaho',
    'St. Reginald Parish': 'Oregon',
    'Staffelter Hof': 'Germany',
    'Stagiaire': 'California',
    'Stamnaki': 'Greece',
    'Straka': 'Austria',
    'Stolpman': 'California',
    'Subject To Change': 'California',
    'Super Real Wines': 'California',
    'Swick': 'Oregon',

    # T
    'Tavijn': 'Italy',
    'Tenuta': 'Italy',
    'Teutonic': 'Oregon',
    'Central Coast Group': 'California',
    'Thomas Puechavy': 'France',
    'Thomas Santamaria': 'France',
    'Tiberi': 'Italy',
    'Topanga Vineyards': 'California',
    'Trail Marker': 'California',
    'Tre Monti': 'Italy',
    'Troupis': 'Greece',
    'Turley': 'California',
    'Two Shepherds': 'California',
    'Tzora Vineyards': 'Israel',

    # U
    'Ultraviolet': 'California',
    'Umathum': 'Austria',
    'Union Sacre': 'California',

    # V
    'Valerie Forgues': 'France',
    'Valravn': 'California',
    'Vina Maitia': 'Chile',
    'Vinca Minor': 'California',
    'Vin De California': 'California',
    'Vini Rabasco': 'Italy',
    'Vino Lauria': 'Italy',
    'Vinos Pijoan': 'Mexico',
    'Vinovore': 'California',
    'Vins Nus': 'Spain',
    'Vinyer De La Ruca': 'France',
    'Viteadovest': 'Italy',
    'Vivanterre': 'France',

    # W
    'Walter Scott': 'Oregon',
    'Wavy Wines': 'California',
    'Weingut Edelberg': 'Germany',
    'Weinschach': 'Austria',
    'Weninger': 'Hungary',
    'Wenzel': 'Austria',
    'Wild Arc': 'New York',
    'Williams Selyem': 'California',
    'Wohlgemuthheim': 'Austria',
    'Wonderland Project': 'California',
    'Wonderwall': 'California',
    'Wonderwerk': 'California',

    # Y
    'Yetti + The Kokonut': 'Australia',

    # Z
    'Zebedeo': 'Spain',
    'Zeit': 'Austria',
    'Zillamina': 'Spain',
    'Ziniel': 'Austria',
    'Zumo': 'California',
}